# Generated by Django 5.1.4 on 2025-01-09 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jovialApi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follower',
            old_name='follower',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='poster',
            new_name='user',
        ),
    ]
