# Generated by Django 5.1.4 on 2025-01-10 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jovialApi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follower',
            old_name='following',
            new_name='follow',
        ),
    ]
