# Generated by Django 5.1.4 on 2025-01-10 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jovialApi', '0002_rename_following_follower_follow'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('username', 'post')},
        ),
    ]
