# Generated by Django 5.1.4 on 2025-01-09 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jovialApi', '0002_rename_follower_follower_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tag',
        ),
    ]
