# Generated by Django 5.1.4 on 2025-01-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jovialApi', '0003_alter_like_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, max_length=128),
        ),
        migrations.AlterUniqueTogether(
            name='follower',
            unique_together={('username', 'follow')},
        ),
    ]
