# Generated by Django 5.1.4 on 2025-01-09 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jovialApi', '0004_alter_follower_following_alter_follower_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follower',
            old_name='user',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='user',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='username',
        ),
    ]
