# Generated by Django 4.2.7 on 2023-12-13 13:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_alter_like_time_alter_posts_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 12, 13, 19, 27, 44, 969599)),
        ),
        migrations.AlterField(
            model_name='posts',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 13, 19, 27, 44, 969599)),
        ),
    ]
