# Generated by Django 4.2.7 on 2023-12-13 16:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_alter_like_time_alter_posts_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 12, 13, 22, 12, 48, 442371)),
        ),
        migrations.AlterField(
            model_name='posts',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 13, 22, 12, 48, 441372)),
        ),
    ]
