# Generated by Django 4.2.7 on 2024-04-30 18:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0012_alter_like_time_alter_posts_time_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='time',
            field=models.TimeField(default=datetime.datetime(2024, 4, 30, 23, 56, 0, 805480)),
        ),
        migrations.AlterField(
            model_name='posts',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 30, 23, 56, 0, 805480)),
        ),
    ]
