# Generated by Django 4.2.7 on 2024-05-01 16:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0014_alter_like_time_alter_posts_time_userpic_userbio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='time',
            field=models.TimeField(default=datetime.datetime(2024, 5, 1, 22, 2, 32, 315095)),
        ),
        migrations.AlterField(
            model_name='posts',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 1, 22, 2, 32, 314069)),
        ),
        migrations.AlterField(
            model_name='userpic',
            name='pic',
            field=models.ImageField(upload_to=''),
        ),
    ]
